### ISSUE TITLE
No file to be quantized!

### ISSUE THREAD

**Issue by liu-x-p** [bootphon/zerospeech2021#4]
Hi, when I run `scripts/quantize_audio.py`, it asserts error

> Looking for all flac files in ./data/LibriSpeech/dev-clean/
> Ran in an error while loading ./data/LibriSpeech/dev-clean/_seqs_cache.txt: [Errno 2] No such file or directory: './data/LibriSpeech/dev-clean/_seqs_cache.txt'
> Could not load cache, rebuilding
> 0it [00:00, ?it/s]
> Ran in an error while saving ./data/LibriSpeech/dev-clean/_seqs_cache.txt: [Errno 2] No such file or directory: './data/LibriSpeech/dev-clean/_seqs_cache.txt'
> Seems like the _seq_cache.txt does not contain the correct extension, reload the file list
> 0it [00:00, ?it/s]
> Ran in an error while saving ./data/LibriSpeech/dev-clean/_seqs_cache.txt: [Errno 2] No such file or directory: './data/LibriSpeech/dev-clean/_seqs_cache.txt'
> Done! Found 0 files!
> Writing args to ./quantized/LibriSpeech/dev-clean/_info_args.json
> Traceback (most recent call last):
>   File "scripts/quantize_audio.py", line 264, in <module>
>     main(args)
>   File "scripts/quantize_audio.py", line 174, in main
>     "No file to be quantized!"
> AssertionError: No file to be quantized!

Firstly I thought that was because I didn't have the file __seq_cache.txt_ , but after I used cpc_audio to produce the file, it still went wrong. 
Can you help me with it?

**Comment by liu-x-p** [comment]
The command I use is
```
python scripts/quantize_audio.py \
        --pathClusteringCheckpoint /home/speech/Self-Supervised-Speech-Pretraining-and-Representation-Learning-master/Self-Supervised-Speech-Pretraining-and-Representation-Learning/result/result_transformer/mockingjay_lib_fbBase/states-270000.ckpt \
        --pathDB ./data/LibriSpeech/dev-clean/ \
        --pathOutputDir ./quantized/LibriSpeech/dev-clean/ \
        --file_extension flac
```
